export const ALL_BRANDS_REQUEST = 'ALL_BRANDS_REQUEST'
export const ALL_BRANDS_SUCCESS = 'ALL_BRANDS_SUCCESS'
export const ALL_BRANDS_FAIL = 'ALL_BRANDS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
